const services = [
  { title: 'HR', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Rekrytering', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Bemanning', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Rådgivning', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Renovering', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Snickeri', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Måleri', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' },
  { title: 'Stenläggning', description: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur dolorum repudiandae sunt nihil adipisci accusamus, ratione rerum exercitationem cumque non voluptatem delectus eaque ipsa, eos molestiae praesentium qui sint dolor.' }
];

export default services;